
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 13 11:45:53 COT 2015
//----------------------------------------------------

package al_richardchimbo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINLINEA = 6;
  public static final int error = 1;
  public static final int ONZA = 5;
  public static final int LIBRA = 4;
  public static final int KILOGRAMO = 3;
  public static final int OPERADOR = 2;
  public static final int EOF = 0;
  public static final int VARIABLE = 7;
}

